const Licensing = (() => {
  const STORAGE_KEY = "licenseKey";
  const MANAGED_KEY = "enterpriseLicenseKey";
  const ALLOWED_PLANS = new Set(["pro", "enterprise"]);

  // Generated by scripts/generate-license-keys.mjs. Only the public key ships.
  const PUBLIC_KEY_SPKI_BASE64 =
    globalThis.__CONSOLE_PASTE_TEST_PUBLIC_KEY__ ||
    "MCowBQYDK2VwAyEAVDETkQ+rxz+gDpUC8dIPm3dCckoi8zZMqVeqnGOOOp8=";

  function decodeBase64Url(value) {
    const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
  }

  function parsePayload(encoded) {
    const bytes = decodeBase64Url(encoded);
    return JSON.parse(new TextDecoder().decode(bytes));
  }

  async function importPublicKey() {
    const binary = Uint8Array.from(atob(PUBLIC_KEY_SPKI_BASE64), (character) =>
      character.charCodeAt(0)
    );
    return crypto.subtle.importKey(
      "spki",
      binary,
      { name: "Ed25519" },
      false,
      ["verify"]
    );
  }

  async function verify(licenseKey) {
    const [encodedPayload, encodedSignature, extra] = String(licenseKey || "")
      .trim()
      .split(".");
    if (!encodedPayload || !encodedSignature || extra) {
      throw new Error("Der Lizenzcode hat ein ungültiges Format.");
    }

    const publicKey = await importPublicKey();
    const valid = await crypto.subtle.verify(
      "Ed25519",
      publicKey,
      decodeBase64Url(encodedSignature),
      new TextEncoder().encode(encodedPayload)
    );
    if (!valid) throw new Error("Die Signatur des Lizenzcodes ist ungültig.");

    const payload = parsePayload(encodedPayload);
    if (payload.version !== 1 || !ALLOWED_PLANS.has(payload.plan)) {
      throw new Error("Der Lizenzcode enthält keinen unterstützten Tarif.");
    }
    if (!payload.licenseId || typeof payload.licenseId !== "string") {
      throw new Error("Dem Lizenzcode fehlt eine Lizenznummer.");
    }
    if (payload.expiresAt && Date.parse(payload.expiresAt) <= Date.now()) {
      throw new Error("Die Lizenz ist abgelaufen.");
    }

    return {
      plan: payload.plan,
      licenseId: payload.licenseId,
      expiresAt: payload.expiresAt || null,
      source: "license"
    };
  }

  async function managedLicense() {
    try {
      const managed = await chrome.storage.managed.get(MANAGED_KEY);
      if (!managed[MANAGED_KEY]) return null;
      const entitlement = await verify(managed[MANAGED_KEY]);
      return { ...entitlement, source: "enterprise-policy" };
    } catch {
      return null;
    }
  }

  async function getEntitlement() {
    const managed = await managedLicense();
    if (managed) return managed;

    const stored = await chrome.storage.local.get(STORAGE_KEY);
    if (!stored[STORAGE_KEY]) {
      return { plan: "free", licenseId: null, expiresAt: null, source: "default" };
    }

    try {
      return await verify(stored[STORAGE_KEY]);
    } catch {
      await chrome.storage.local.remove(STORAGE_KEY);
      return { plan: "free", licenseId: null, expiresAt: null, source: "default" };
    }
  }

  async function activate(licenseKey) {
    const entitlement = await verify(licenseKey);
    await chrome.storage.local.set({ [STORAGE_KEY]: String(licenseKey).trim() });
    return entitlement;
  }

  async function deactivate() {
    await chrome.storage.local.remove(STORAGE_KEY);
  }

  return { activate, deactivate, getEntitlement };
})();

globalThis.Licensing = Licensing;
